changed-code
alexandrevilain/temporal-operator pull request #476
Opened 2023-08-25 09:44 UTC by Demch1k

Hello!
We encountered 2 main problems when tried deploy temporal-operator in our k8s clusters.
1. In our clusters we have adminission controler that checking existing resource limits on every pod in the cluster. If you don't pass resources to pod you will not able to deploy it.
2. We work with s3 compatible storage provider that supports only path styled url's.

2023-08-25 11:42 UTC, Demch1k commented
@alexandrevilain
I suppose my changes are not influent on to failed pipilens, how do you think?

2023-08-26 16:41 UTC, alexandrevilain requested changes
Hi! Thanks for your contribution! Code is ok for me, could you please amend your commit message to explain what you did instead of `changed-code` ? Thanks :)

2023-08-26 16:50 UTC, Demch1k commented
@alexandrevilain
Thanks. Changed message for commit.

2023-08-26 16:51 UTC, alexandrevilain approved these changes
Thanks! 🎉

2023-08-26 17:47 UTC, merged