Add ui does description
alexandrevilain/temporal-operator pull request #585
Opened 2023-12-26 07:00 UTC by Aoao54

Add ui does description

2023-12-26 10:33 UTC, yujunz approved these changes

2023-12-26 12:43 UTC, alexandrevilain reviewed
Thanks for this useful contribution !! 
I added some suggestions :)

2023-12-26 12:43 UTC, alexandrevilain commented on docs/features/temporal-ui.md
> +Temporal-operator supports configuring WEB UI for Temporal clusters. You can get more informations about Event histories backup on [Temporal documentation](https://docs.temporal.io/web-ui).
```suggestion
Temporal-operator supports configuring web UI for Temporal clusters. You can get more informations about web UI on [Temporal documentation](https://docs.temporal.io/web-ui).
```

2023-12-26 12:43 UTC, alexandrevilain commented on docs/features/temporal-ui.md
> +Ingress is an optional ingress configuration for the UI. If lived empty, no ingress configuration will be created and the UI will only by available trough ClusterIP service.
```suggestion
Ingress is an optional ingress configuration for the UI. If leaved empty, no ingress configuration will be created and the UI will only by available through ClusterIP service.
```

2023-12-26 12:43 UTC, alexandrevilain commented on docs/features/temporal-ui.md
> +Override UI deployment can be used to set [Web UI env vars](https://docs.temporal.io/references/web-ui-environment-variables).
```suggestion
Web UI overrides can be used to set [web UI environment variables](https://docs.temporal.io/references/web-ui-environment-variables).
```

2023-12-26 12:52 UTC, yujunz commented
Just realize the description should be "Add ui docs ~does~ description".

2023-12-26 12:53 UTC, yujunz requested changes
Minor comments on commit message.

2023-12-28 05:55 UTC, alexandrevilain approved these changes
Thanks !!

2023-12-28 05:55 UTC, merged