feat(overrides): add JSON patch for deployments
alexandrevilain/temporal-operator pull request #875
Opened 2024-12-12 19:21 UTC by andrewbelu

Add additional functionality to override spec to allow for JSON patching. This is to allow users to patch arrays inside deployment overrides, as this functionality is not possible with StrategicPatchMerge. Follows similar functionality to what Kustomize provides.

2024-12-12 19:23 UTC, andrewbelu commented
Addresses https://github.com/alexandrevilain/temporal-operator/issues/793

2024-12-14 22:33 UTC, alexandrevilain requested changes
Thanks for this awesome contribution. 
I really like this! 
JsonPatch is way more common than overrides.
Both are maybe too much. 

Maybe we can provide this feature for every components (adminstools, services, monitoring, istio, ...) ? In a next PR. This is already a good start!

2024-12-14 22:33 UTC, alexandrevilain commented on webhooks/temporalcluster_webhook.go
> +					fmt.Sprintf("Can't set JsonPatch when Spec is set on Deployment override"),
```suggestion
					"Can't set JsonPatch when Spec is set on Deployment override",
```
No need for `Sprintf` :)

2024-12-14 22:33 UTC, alexandrevilain commented on webhooks/temporalcluster_webhook.go
> +						fmt.Sprintf("Can't set JsonPatch when Spec is set on Deployment override"),
```suggestion
						"Can't set JsonPatch when Spec is set on Deployment override",
```

2024-12-22 13:16 UTC, alexandrevilain approved these changes

2025-02-04 16:19 UTC, andrewbelu commented
Hey @alexandrevilain, anything you needed from me to get this in?

2025-02-21 08:38 UTC, merged